### PR TITLE
Improved usage of GitHub Actions; fix Decider test

### PR DESCRIPTION
**Pull request by JostMigenda**
## Description

* adds more recent Python version to test matrix
* adds `make doc` and `make format` as suggested in #23 
* run `make lint` only on most recent Python version (since we don’t expect linting to vary between Python versions)

Note that `make doc` [currently fails](https://github.com/SNEWS2/hop-SNalert-app/runs/2842896212?check_suite_focus=true). Help wanted on solving that! (Note also that this failure only affects the test under Python 3.9, since `make doc` (like `make lint`) is skipped under older Python versions.)

## Checklist

* ~[ ] All new functions and classes are documented and adhere to Google doc style (3.8.3-3.8.6 of [this](http://google.github.io/styleguide/pyguide.html#383-functions-and-methods) document)~
* ~[ ] Add/update sphinx documentation with any relevant changes.~
* ~[ ] Add/update pytest-style tests in `/tests`, ensuring sufficient code coverage.~
* [x] `make test` runs without errors.
* [x] `make lint` doesn't give any warnings.
* [x] `make format` doesn't give any code formatting suggestions.
* [x] `make doc` runs without errors and generated docs render correctly.
* [x] Check that CI pipeline run on this PR passes all stages.
* [ ] Review signoff by at least one developer.

NOTE: If this PR relates to a release, open and reference an issue with the Release checklist template.

### CODE REVIEW

**Comment by bfc5288** [comment]
@JostMigenda This looks reasonable, and I think I know what is wrong with `make doc`.

The current setup assumes that the developer is running `make doc` after installing the required sphinx packages (via `pip install .[docs]`, see [setup.py](https://github.com/SNEWS2/hop-SNalert-app/blob/JostMigenda/GitHubAction/setup.py#L37)), so I would expect this to work if that `pip` command is added to the `make doc` portion of the CI.

I am surprised that `make test` and `lint` don't fail without `pip install .[dev]`, but I must be missing something about those runs.

**Comment by JostMigenda** [comment]
I’ve added `pip install .[docs]` to the action. `make doc` still fails, but at a later stage now. Is anyone here familiar enough with Sphinx that they know what’s going on?

Note that `pip install .[dev]` is happening in the build step; those tools remain available for all following steps in the same job.

Finally, it looks like this action is triggered twice for every commit: Once because it triggers on every (commit to a) `pull_request` and once because it triggers on every `push` to this repo and the branch I want to merge with this PR is in this same repo. I’ll try to fix this in the next commit …

**Comment by myNameIsPatrick** [comment]
> I’ve added pip install .[docs] to the action. make doc still fails, but at a later stage now. Is anyone here familiar enough with Sphinx that they know what’s going on?

It looks like there's a new major release of Sphinx (4.x) as of last month that is causing issues. A quick fix to get around this could be to pin sphinx (`sphinx < 4.0`) in https://github.com/SNEWS2/hop-SNalert-app/blob/master/setup.py#L38. I'd imagine this would break the `hop-client` docs as well as other projects I've set up with a similar setup, so I can take a crack at fixing this once I figure out what all has changed.

**Comment by JostMigenda** [comment]
Using https://github.com/fkirc/skip-duplicate-actions this appears to have worked [on the second try](https://github.com/SNEWS2/hop-SNalert-app/pull/29/checks?check_run_id=2944233969).

**Comment by myNameIsPatrick** [comment]
FYI it looks like #28 fixes the documentation issues so once that's approved/merged those failures should be fixed here.

**Comment by JostMigenda** [comment]
Test failures are not related to Sphinx this time but to an AssertionError in [test_decider.py](https://github.com/SNEWS2/hop-SNalert-app/blob/master/tests/test_decider.py#L23). It looks like that started to fail when @habig merged my PR #22 a few days ago.
I think I found an issue in the test data … fixed in the next commit, let’s see if that works.

**Comment by JostMigenda** [comment]
Yep, that fixed it. All checks are passing now and the Sphinx issues are indeed solved; so I think this is ready to be merged?

**Review by bfc5288 — APPROVED** [review]
@JostMigenda Good catch. This looks ready to me, feel free to merge when convenient.

**Pull request merged**
