### PR TITLE
Fix/makefile ci

### PR DESCRIPTION
**Pull request by bfc5288**
## Description

This PR addresses the issues encountered when running `make` checklist entries for new PRs, as mentioned in #22. The problem was that the `make` commands would go through all files in the current working directory (not just the SNEWS codebase and tests), so other files would be parsed and could cause red herring errors or hanging loops.

After addressing those issues, running the `make doc` check succeeds with the following issues/warnings:
```
# make doc
...
WARNING: autodoc: failed to import module 'IDecider' from module 'snews'; the following exception was raised:
No module named 'snews.IDecider'
/home/bfc5288/git.hub/scimma/hop-SNalert-app/doc/api/decider.rst:4: WARNING: duplicate label decider, other instance in /home/bfc5288/git.hub/scimma/hop-SNalert-app/doc/user/architecture.rst
WARNING: autodoc: failed to import module 'IStorage' from module 'snews'; the following exception was raised:
No module named 'snews.IStorage'
/home/bfc5288/git.hub/scimma/hop-SNalert-app/doc/index.rst:7: WARNING: toctree contains reference to nonexisting document 'user/protocols'
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/bfc5288/git.hub/scimma/hop-SNalert-app/doc/user/protocol.rst: WARNING: document isn't included in any toctree
...
```
This caused the `snews.decider` and `snews.storage` html doc files to not generate, and `protocol` was omitted due to a typo (see the [old docs here](https://web.archive.org/web/20210616175647/https://hop-snalert-app.readthedocs.io/en/stable/api/api.html)).

This PR fixes these issues, resolving the empty Decider and Storage entries in the API docs and the missing Protocol doc entry.

## Checklist

* [ ] All new functions and classes are documented and adhere to Google doc style (3.8.3-3.8.6 of [this](http://google.github.io/styleguide/pyguide.html#383-functions-and-methods) document)
* [ ] Add/update sphinx documentation with any relevant changes.
* [ ] Add/update pytest-style tests in `/tests`, ensuring sufficient code coverage.
* [x] `make test` runs without errors.
* [x] `make lint` doesn't give any warnings.
* [x] `make format` doesn't give any code formatting suggestions.
* [x] `make doc` runs without errors and generated docs render correctly.
* [x] Check that CI pipeline run on this PR passes all stages.
* [ ] Review signoff by at least one developer.

NOTE: If this PR relates to a release, open and reference an issue with the Release checklist template.

### CODE REVIEW

**Comment by bfc5288** [comment]
Note that this doesn't address #23, though those changes could still be considered in-scope for this PR. I believe one reason for not putting in all of the checklist items into the Github CI workflow initially was to reduce how much of the (limited) cloud time the CI uses (e.g., `make doc` would run on every push even if the docs weren't changed). Though this may just be developer preference so I think changes to this are possible.

**Comment by bfc5288** [comment]
@JostMigenda @AmandaDepoian Do you have any thoughts on this? We could put more of the checklist items into the CI but see my comment above.

**Comment by JostMigenda** [comment]
@bfc5288 I think we’re orders of magnitude away from hitting the [usage limits for GitHub Actions](https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration), even on a free plan. So I wouldn’t worry about that.

That said, we could reduce resource usage a bit by e.g. running `make doc` (and `make lint`, and perhaps others?) only under the most recent Python version; and only run things like `make test`, where it’s reasonably likely to observe differences between Python versions under all Python versions.

**Comment by JostMigenda** [comment]
Take a look at #29, which implements my suggestions (and adds a few more improvements).

**Comment by bfc5288** [comment]
@myNameIsPatrick These are small changes, but could you give this a quick once-over before merging? I'd like to unblock #29

**Review by myNameIsPatrick — APPROVED** [review]
Looks good to me.

**Pull request merged**
